name: uts_mobile
description: "An UI only app, created for midterm exam"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
